# Generated by Django 5.1.5 on 2025-01-29 21:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brewery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=90, null=True)),
                (
                    "city",
                    models.CharField(blank=True, max_length=189, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "founding_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ]
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, default=0.0, max_digits=2
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="beer",
            old_name="ingridients",
            new_name="ingredients",
        ),
        migrations.CreateModel(
            name="BeerBrewery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.beer",
                    ),
                ),
                (
                    "brewery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.brewery",
                    ),
                ),
            ],
        ),
    ]
