# Generated by Django 5.1.5 on 2025-01-29 21:42

from django.db import migrations


def add_default_brewerie(apps, schema_editor):
    """
    Adds a default Brewery entry to all the Beer entries
    without a brewery attached.
    """
    Beer = apps.get_model("base", "Beer")
    Brewery = apps.get_model("base", "Brewery")
    BeerBrewery = apps.get_model("base", "BeerBrewery")

    beers = Beer.objects.all()

    default_brewery, created = Brewery.objects.get_or_create(
        name="Default Brewery", founding_year=1900
    )

    for beer in beers:
        BeerBrewery.objects.get_or_create(
            beer=beer, brewery_id=default_brewery.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_brewery_country"),
    ]

    operations = [
        migrations.RunPython(add_default_brewerie),
    ]
